//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 08:19:56 AM CEST 
//


package com.megatravel.agentskaaplikacija.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.agentskaaplikacija.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.agentskaaplikacija.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AllUsersRequest }
     * 
     */
    public AllUsersRequest createAllUsersRequest() {
        return new AllUsersRequest();
    }

    /**
     * Create an instance of {@link AllUsersResponse }
     * 
     */
    public AllUsersResponse createAllUsersResponse() {
        return new AllUsersResponse();
    }

    /**
     * Create an instance of {@link UserDTO }
     * 
     */
    public UserDTO createUserDTO() {
        return new UserDTO();
    }

    /**
     * Create an instance of {@link AgentLoginRequest }
     * 
     */
    public AgentLoginRequest createAgentLoginRequest() {
        return new AgentLoginRequest();
    }

    /**
     * Create an instance of {@link AgentLoginResponse }
     * 
     */
    public AgentLoginResponse createAgentLoginResponse() {
        return new AgentLoginResponse();
    }

    /**
     * Create an instance of {@link AllRatingsRequest }
     * 
     */
    public AllRatingsRequest createAllRatingsRequest() {
        return new AllRatingsRequest();
    }

    /**
     * Create an instance of {@link AllRatingsResponse }
     * 
     */
    public AllRatingsResponse createAllRatingsResponse() {
        return new AllRatingsResponse();
    }

    /**
     * Create an instance of {@link RatingDTO }
     * 
     */
    public RatingDTO createRatingDTO() {
        return new RatingDTO();
    }

    /**
     * Create an instance of {@link AllMessagesRequest }
     * 
     */
    public AllMessagesRequest createAllMessagesRequest() {
        return new AllMessagesRequest();
    }

    /**
     * Create an instance of {@link AllMessagesResponse }
     * 
     */
    public AllMessagesResponse createAllMessagesResponse() {
        return new AllMessagesResponse();
    }

    /**
     * Create an instance of {@link MessageDTO }
     * 
     */
    public MessageDTO createMessageDTO() {
        return new MessageDTO();
    }

    /**
     * Create an instance of {@link AllReservationsRequest }
     * 
     */
    public AllReservationsRequest createAllReservationsRequest() {
        return new AllReservationsRequest();
    }

    /**
     * Create an instance of {@link AllReservationsResponse }
     * 
     */
    public AllReservationsResponse createAllReservationsResponse() {
        return new AllReservationsResponse();
    }

    /**
     * Create an instance of {@link ReservationDTO }
     * 
     */
    public ReservationDTO createReservationDTO() {
        return new ReservationDTO();
    }

    /**
     * Create an instance of {@link AllUnitsRequest }
     * 
     */
    public AllUnitsRequest createAllUnitsRequest() {
        return new AllUnitsRequest();
    }

    /**
     * Create an instance of {@link AllUnitsResponse }
     * 
     */
    public AllUnitsResponse createAllUnitsResponse() {
        return new AllUnitsResponse();
    }

    /**
     * Create an instance of {@link HousingUnitDTO }
     * 
     */
    public HousingUnitDTO createHousingUnitDTO() {
        return new HousingUnitDTO();
    }

    /**
     * Create an instance of {@link AllTypesRequest }
     * 
     */
    public AllTypesRequest createAllTypesRequest() {
        return new AllTypesRequest();
    }

    /**
     * Create an instance of {@link AllTypesResponse }
     * 
     */
    public AllTypesResponse createAllTypesResponse() {
        return new AllTypesResponse();
    }

    /**
     * Create an instance of {@link TypeDTO }
     * 
     */
    public TypeDTO createTypeDTO() {
        return new TypeDTO();
    }

    /**
     * Create an instance of {@link AllOptionsRequest }
     * 
     */
    public AllOptionsRequest createAllOptionsRequest() {
        return new AllOptionsRequest();
    }

    /**
     * Create an instance of {@link AllOptionsResponse }
     * 
     */
    public AllOptionsResponse createAllOptionsResponse() {
        return new AllOptionsResponse();
    }

    /**
     * Create an instance of {@link OptionDTO }
     * 
     */
    public OptionDTO createOptionDTO() {
        return new OptionDTO();
    }

    /**
     * Create an instance of {@link CreateUnitRequest }
     * 
     */
    public CreateUnitRequest createCreateUnitRequest() {
        return new CreateUnitRequest();
    }

    /**
     * Create an instance of {@link CreateUnitResponse }
     * 
     */
    public CreateUnitResponse createCreateUnitResponse() {
        return new CreateUnitResponse();
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link AddressDTO }
     * 
     */
    public AddressDTO createAddressDTO() {
        return new AddressDTO();
    }

}
