server:
  port: 8082
spring:
  application:
    name: gateway
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  host:
    socket-timeout-millis: 600000
  sensitiveHeaders: Cookie, Set-Cookie