//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 08:41:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.megatravel.com/smestaj/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.megatravel.smestaj.soap;
